#!/usr/bin/env python3
"""Generate TalQ's bundled notification tones as mono 16-bit 44.1 kHz WAVs.

These are 100% original, synthesized from sine/bell envelopes with the
Python standard library only (no deps, no licensing). To replace any tone
with your own recording, just drop a WAV at resources/sounds/<id>.wav and
rebuild — the loader is keyed by filename, not by these generated bytes.

Run:  python scripts/gen-notification-sounds.py
Out:  resources/sounds/{pop,chime,ding,notify,soft,tone}.wav
"""
import math
import os
import struct
import wave

SR = 44100  # sample rate

def _env(t, dur, attack=0.005, release=None):
    """Attack/decay envelope, 0..1. Exponential release for a bell-like tail."""
    if release is None:
        release = dur * 0.9
    if t < attack:
        return t / attack
    rt = t - attack
    return math.exp(-rt / (release / 4.0))

def _write(path, samples):
    # Normalize to -3 dBFS to keep tones at a consistent, non-clipping level.
    peak = max(1e-9, max(abs(s) for s in samples))
    gain = (10 ** (-3.0 / 20.0)) / peak
    with wave.open(path, "w") as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(SR)
        frames = bytearray()
        for s in samples:
            v = int(max(-1.0, min(1.0, s * gain)) * 32767)
            frames += struct.pack("<h", v)
        w.writeframes(bytes(frames))

def _tone(dur, partials, release=None):
    """partials: list of (freq_hz, amplitude)."""
    n = int(SR * dur)
    out = []
    for i in range(n):
        t = i / SR
        e = _env(t, dur, release=release)
        v = sum(a * math.sin(2 * math.pi * f * t) for f, a in partials)
        out.append(v * e)
    return out

def _sweep(dur, f0, f1):
    n = int(SR * dur)
    out = []
    for i in range(n):
        t = i / SR
        e = _env(t, dur)
        f = f0 + (f1 - f0) * (t / dur)
        out.append(math.sin(2 * math.pi * f * t) * e)
    return out

def main():
    here = os.path.dirname(os.path.abspath(__file__))
    outdir = os.path.join(here, "..", "resources", "sounds")
    os.makedirs(outdir, exist_ok=True)

    tones = {
        # short bubble pop — high, very brief
        "pop":    _tone(0.10, [(1200, 1.0), (2400, 0.3)], release=0.06),
        # soft two-note bell (A5 + E6)
        "chime":  _tone(0.55, [(880, 1.0), (1320, 0.6)], release=0.5),
        # classic single ding (G6)
        "ding":   _tone(0.45, [(1568, 1.0), (3136, 0.25)], release=0.42),
        # dry electronic blip (E5, square-ish via odd harmonics)
        "notify": _tone(0.14, [(660, 1.0), (1980, 0.33), (3300, 0.2)], release=0.1),
        # mellow piano-ish note (C5), slow tail
        "soft":   _tone(0.65, [(523.25, 1.0), (1046.5, 0.35)], release=0.6),
        # synthwave rising blip (A4 -> E5)
        "tone":   _sweep(0.22, 440, 659.25),
    }
    for name, samples in tones.items():
        path = os.path.join(outdir, f"{name}.wav")
        _write(path, samples)
        print(f"wrote {os.path.relpath(path, os.path.join(here, '..'))} "
              f"({len(samples)} samples, {len(samples)/SR:.2f}s)")

if __name__ == "__main__":
    main()
