#!/usr/bin/env python3
"""Generate EmojiData_generated.cpp from emoji-datasource JSON.

Usage: python scripts/gen-emoji-data.py resources/emoji-data-source.json src/core/EmojiData_generated.cpp
"""
import json
import sys
from pathlib import Path

CATEGORY_MAP = {
    "Smileys & Emotion": "Smileys",
    "People & Body":     "People",
    "Animals & Nature":  "Animals",
    "Food & Drink":      "Food",
    "Activities":        "Activities",
    "Travel & Places":   "Travel",
    "Objects":           "Objects",
    "Symbols":           "Symbols",
    "Flags":             "Flags",
}

# Short-form text shortcuts — must be maintained manually since the dataset
# doesn't ship them.
SHORT_FORMS = {
    "1F642": [":)", ":-)"],                 # slightly_smiling_face
    "1F603": [":D", ":-D"],                 # smiley
    "1F61B": [":P", ":-P", ":p", ":-p"],    # stuck_out_tongue
    "1F61E": [":(", ":-("],                 # disappointed_face
    "1F609": [";)", ";-)"],                 # wink
    "1F62E": [":o", ":-o", ":O", ":-O"],    # open_mouth
    "1F610": [":|", ":-|"],                 # neutral_face
    "1F615": [":/", ":-/"],                 # confused
    "2764":  ["<3"],                        # heart
    "1F494": ["</3"],                       # broken_heart
    "1F618": [":*", ":-*"],                 # kissing_heart
    "1F62D": [":'("],                       # loudly_crying_face
    "1F60E": ["B)", "B-)"],                 # sunglasses
}


def unified_to_codepoints(unified: str) -> str:
    """'1F600' -> '\\U0001F600' escape sequence for C++."""
    return "".join(
        f"\\U{int(c, 16):08X}" for c in unified.split("-")
    )


def cxx_string(s: str) -> str:
    """Escape arbitrary Python string for a C++ QStringLiteral argument."""
    escaped = s.replace("\\", "\\\\").replace('"', '\\"')
    return f'QStringLiteral("{escaped}")'


def main(src_json: Path, out_cpp: Path):
    data = json.loads(src_json.read_text(encoding="utf-8"))

    lines = [
        '// GENERATED by scripts/gen-emoji-data.py — DO NOT EDIT.',
        '#include "EmojiData.h"',
        '',
        'namespace EmojiData {',
        '',
        'void loadGeneratedData(QVector<EmojiEntry> &out)',
        '{',
        f'    out.reserve({len(data)});',
        '',
    ]

    for e in data:
        cat = CATEGORY_MAP.get(e.get("category", ""))
        if not cat:
            continue  # skip component emojis (skin tones themselves)
        cp = unified_to_codepoints(e["unified"])
        name = e.get("name") or e.get("short_name", "")
        shortcodes = [f":{sn}:" for sn in e.get("short_names", [])]
        short_forms = SHORT_FORMS.get(e["unified"], [])
        variants = []
        for tone_key, tone_data in (e.get("skin_variations") or {}).items():
            variants.append(unified_to_codepoints(tone_data["unified"]))
        keywords = e.get("short_names", []) + [name.lower()]

        lines.append('    out.append({')
        lines.append(f'        QStringLiteral(u"{cp}"),')
        lines.append(f'        Category::{cat},')
        lines.append(f'        {cxx_string(name.lower())},')
        lines.append('        {' + ", ".join(cxx_string(s) for s in shortcodes) + '},')
        lines.append('        {' + ", ".join(cxx_string(s) for s in short_forms) + '},')
        if variants:
            lines.append('        {' + ", ".join(f'QStringLiteral(u"{v}")' for v in variants) + '},')
        else:
            lines.append('        {},')
        lines.append('        {' + ", ".join(cxx_string(k) for k in keywords) + '},')
        lines.append('    });')

    lines += [
        '}',
        '',
        '} // namespace EmojiData',
        '',
    ]

    out_cpp.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {out_cpp} ({len(data)} entries)")


if __name__ == "__main__":
    main(Path(sys.argv[1]), Path(sys.argv[2]))
